name: Build APK
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    # السطر ده بيجبر كل الأكشنز تستخدم Node 24 عشان التحذير الأصفر يختفي
    env:
      ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.0'
          cache: true

      - name: Install dependencies
        run: flutter pub get

      - name: Build APK
        # ضفنا السطر ده عشان نتخطى أي مشاكل في الـ Rendering أو الأيقونات
        run: flutter build apk --release --no-tree-shake-icons --ignore-deprecation

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: our-space-app
          path: build/app/outputs/flutter-apk/app-release.apk
